version: "2"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"

  suricata:
    build: ./suricata
    privileged: true
    network_mode: host
    environment:
      - INTERFACE
    volumes:
      - log-suricata:/var/log/suricata:z

  evebox:
    image: jasonish/evebox:master
    volumes:
      - log-suricata:/var/log/suricata:z
    links:
      - elasticsearch
    ports:
      - 5636:5636
    command: --input /var/log/suricata/eve.json -e http://elasticsearch:9200

  curator:
    build: ./curator
    links:
      - elasticsearch

  # ICS Honeypot - https://github.com/mushorg/conpot
  conpot:
    image: honeynet/conpot
    ports:
      - 102:102
      - 502:502
      - 161:161/udp
    network_mode: bridge
    command: conpot --template default

  # MTPot - Mirai/Telnet honeypot.
  # https://github.com/Cymmetria/MTPot
  mtpot:
    build: ./mtpot
    ports:
      - "23:23"
    network_mode: bridge

volumes:
  log-suricata:
